markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links

optional_front_matter:
  remove_originals: true

relative_links:
  enabled:     true
  collections: false
  browser_only: true

