auto: true
server: true
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - 'jekyll-toc'
  
defaults:
  -
    scope:
      path: ""
    values:
      image: true
      toc: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      layout: "post"
