defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links

optional_front_matter:
  remove_originals: true

relative_links:
  enabled:     true
  collections: false
